### ISSUE TITLE
TXManager正常启动后，启动demo中的客户端（spring版）后 ，TXManager反序列化异常

### ISSUE THREAD

**Issue by IcyRoc** [codingapi/txlcn-demo#1]
TXManager报错：
io.netty.handler.codec.DecoderException: com.codingapi.txlcn.commons.exception.SerializerException: Protocol message contained an invalid tag (zero).

Client报错：
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 1048576: 168898871 - discarded

**Comment by 1991wangliang** [comment]
应该是版本不一致导致的， 请确保TxClient与TxManager版本号一致。
