### ISSUE TITLE
提示txlcn-demo-common:jar:1.0.0异常

### ISSUE THREAD

**Issue by wing514895968** [codingapi/txlcn-demo#3]
异常出错信息：
[ERROR] Failed to execute goal on project txlcn-demo-dubbo-service-a: Could not resolve dependencies for project org.txlcn.demo:txlcn-demo-dubbo-service-a:jar:1.0.0: Could not find artifact org.txlcn.demo:txlcn-demo-common:jar:1.0.0 in alimaven (http://maven.aliyun.com/nexus/content/groups/public/) -> [Help 1]

**Comment by RayoForever** [comment]
这个应该是txlcn-demo-common:jar:1.0.0里面的jar跟你项目里面的jar有冲突了   你的分析下里面的maven冲突

**Comment by ujued** [comment]
以解决
