### ISSUE TITLE
TX-MANAGER

### ISSUE THREAD

**Issue by gongchao8888** [codingapi/txlcn-demo#6]
我自己建的一个tm-manager工程，引入了 
<dependency>
            <groupId>com.codingapi.txlcn</groupId>
            <artifactId>txlcn-tm</artifactId>
            <version>5.0.2.RELEASE</version>
 </dependency>

启动时候报错：Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
在官网上-》文档-》快速开启-TM配置与启动中，创建的数据表的作用是什么？我在本地也创建了表，但是还是提示这个错误，配置文件mysql的连接也有配置

**Comment by ujued** [comment]
密码不正确，对吧。TM中有一些东西需要的持久化存储

**Comment by gongchao8888** [comment]
用户名密码都是正确的，怎么还会提示密码错误

**Comment by gongchao8888** [comment]
create connection error, url: jdbc:mysql://127.0.0.1:3306/tx-manager?characterEncoding=UTF-8, errorCode 1045, state 28000
我不知道这个url你是在哪里定义的，我在配置文件中 定义了自己的数据库连接，还是提示这个错误
难道是定义死了数据库的连接地址就得是这个，用户名必须是root，密码必须是root？

**Comment by ujued** [comment]
application.properties 加载顺序如下：
0、命令行启动参数指定
1、file:./config/（当前jar目录下的config目录）
2、file:./（当前jar目录）
3、classpath:/config/（classpath下的config目录）
4、classpath:/（classpath根目录）

我们在4这个地方提供了一个配置文件，你可以在优先级高的地方覆盖

**Comment by gongchao8888** [comment]
哦，已解决，jar包中的是properties配置文件，我使用的yml，优先级别呀低些，所以我的配置无效

**Comment by gongchao8888** [comment]
谢谢
